name: Deploy

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: sky-edu-pc
jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: 进入服务器并拉取最新镜像
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "********* Delete Exist Image *********"
            docker rmi swr.cn-east-3.myhuaweicloud.com/gaozewen/${{ env.PROJECT_NAME }}:v1 || true
            echo "********* Delete Success *********"
            echo "********* Login Huawei Docker Hub *********"
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} \
                         -p ${{ secrets.DOCKER_HUB_PASSWORD }} \
                         swr.cn-east-3.myhuaweicloud.com
            echo "********* Start Pull Latest Image *********"
            docker pull swr.cn-east-3.myhuaweicloud.com/gaozewen/${{ env.PROJECT_NAME }}:v1
            echo "********* Pull Success *********"

      - name: 停止并删除旧容器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "********* 停止容器 *********"
            docker stop ${{ env.PROJECT_NAME }} || true
            echo "********* 删除容器 *********"
            docker rm ${{ env.PROJECT_NAME }} || true
            echo "********* ALL CLEAR *********"

      - name: 运行新容器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker run -d \
                       --restart unless-stopped \
                       --name ${{ env.PROJECT_NAME }} \
                       -p 5173:80 \
                       swr.cn-east-3.myhuaweicloud.com/gaozewen/${{ env.PROJECT_NAME }}:v1
